networks:
  default:
    external: true
    name: roboshop

volumes:
  mongodb: #docker volume create mongodb
  redis:
  mysql:
  rabbitmq:

services:
  # docker run -d --name mongodb mongodb:1
  mongodb:
    container_name: mongodb
    image: mongodb:v1
    volumes:
    - source: mongodb
      target: /data/db
      type: volume
    # networks:
    # - roboshop
    
  catalogue:
    container_name: catalogue
    image: catalogue:v1
    depends_on:
    - mongodb

  web:
    container_name: web
    image: web:v1
    ports:
      - "80:80"
    depends_on:
    - catalogue
  
  redis:
    image: redis
    container_name: redis
    volumes:
    - source: redis
      target: /data
      type: volume

  user:
    container_name: user
    image: user:v1
    depends_on:
      - redis
      - mongodb
  
  cart:
    container_name: cart
    image: cart:v1
    depends_on:
      - redis
      - catalogue
  
  mysql:
    container_name: mysql
    image: mysql:v1
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume

  shipping:
    container_name: shipping
    image: shipping:v1
    depends_on:
    - mysql
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
    - source: rabbitmq
      target: /var/lib/rabbitmq
      type: volume

  payment:
    container_name: payment
    image: payment:v1
    depends_on:
    - cart
    - user
    - rabbitmq
    

    




  